### ISSUE TITLE
Snort IDS

### ISSUE THREAD

**Issue by mattjay** [sooshie/secrepo#1]
This is an awesome set of data you have. Any chance you've got some Snort IDS you could add to the pile?

**Comment by sooshie** [comment]
not immediately handy, but I could probably generate some in the next few days.

**Comment by sooshie** [comment]
1 set (maccdc2012), 2 log formats added (full and fast alert format). I'll try and get the threatglass corpus I have run through as well.

**Comment by sooshie** [comment]
Added Threatglass snort logs as well.

**Comment by mattjay** [comment]
Thank you! This sped up me being able to write this:

https://github.com/mattjay/snortStats

Cheers!
