### ISSUE TITLE
Request for Update with an ML for Security Article

### ISSUE THREAD

**Issue by faizann24** [sooshie/secrepo#13]
Wrote this article recently. Would love to have it in the list.
https://faizanahmad.tech/blog/2020/02/phishytics-machine-learning-for-phishing-websites-detection

**Comment by sooshie** [comment]
While it's a nice write-up I don't really keep track of articles on the site. However, if you publish a dataset along with the article I'm happy to add it.

**Comment by faizann24** [comment]
Thanks for responding back. The data set is already available publicly and is linked in the article. There is also a github repo to replicate the experiments and make your own models.
