### ISSUE TITLE
how to download Information Security Centre of Excellence (ISCX) dataset

### ISSUE THREAD

**Issue by aodiwei** [sooshie/secrepo#6]
I can't find any download link on official website, do you have the dataset copy? can you help me? thx

**Comment by sooshie** [comment]
You have to email a.habibi.l@unb.ca, they're not available for direct download.

**Comment by aodiwei** [comment]
thx very much, i have downloaded the dataset, but i have a problem, can you help me?
All traces in List of malicious IPs are malicous trace?
for example: we can regard all traces of 147.32.84.180（source ip ) as Neris's trace which is a malicious.
is it right?
Or i should clean non-malicious trace of 147.32.84.180（source ip ) by myself?
